# ambiente dev MVP

paths:
  data_sources: "data_sources/samples/"
  staging: "staging/"
  logs: "logs/platform.log"
  metadata_catalog: "metadata/catalog.json"
  blockchain_log: "blockchain/audit_log.json"

validation:
  isolation_forest:
    contamination: 0.02
    random_state: 42
  dbscan:
    eps: 0.5
    min_samples: 5

versioning:
  lakefs:
    repository: "veritrace-repo"
    endpoint: "http://localhost:8000/api/v1"
    access_key: "MOCK_ACCESS_KEY"
    secret_key: "MOCK_SECRET_KEY"

blockchain:
  bigchaindb:
    endpoint: "http://localhost:9984"

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '%(asctime)s [%(levelname)s] %(name)s %(message)s'
  handlers:
    console:
      level: 'INFO'
      class: 'logging.StreamHandler'
      formatter: 'standard'
    file:
      level: 'DEBUG'
      class: 'logging.handlers.RotatingFileHandler'
      formatter: 'standard'
      filename: 'logs/platform.log'
      maxBytes: 10485760
      backupCount: 3
  loggers:
    '':
      handlers: ['console', 'file']
      level: 'INFO'
      propagate: False
