name: Release and Homologation Workflow

on:
  push:
    branches:
      - 'release/**'

jobs:
  deploy-homologation:
    runs-on: ubuntu-latest
    environment: homologation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Deploy to Homologation Environment
        run: |
          echo "🚀 Deploying to homologation..."

  create-pr-to-main:
    runs-on: ubuntu-latest
    needs: [deploy-homologation]
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request to Main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: Promote release to main"
          title: "Release ${{ github.ref_name }} to Production"
          body: "This PR was automatically created to merge the release branch `${{ github.ref_name }}` into `main` for production deployment."
          base: "main"
          branch: "${{ github.ref_name }}"
          labels: "automated-pr, release"